#!/usr/bin/expect
#
#       file: execute
set timeout 7

set cmd [lrange $argv 0 end]
set password [exec cat .rootpw.txt]

eval spawn -noecho $cmd
expect "*assword:"
send "$password\r"
expect {
        "*#" {
                interact
        } "*password:" {
                send "$password\r"
                interact
        } timeout {
                send_user "connection timed out\n"
                exit 2
        }
}
exit
